version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - frontend
    networks:
      - quill-network
    volumes:
      - quill-volume:/data
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - quill-network

networks:
  quill-network:
    driver: bridge

volumes:
  quill-volume: