name: ci
 
on:
 push:
  branches: [ "master" ]
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   -
    name: Check current directory and list files
    run: |
     pwd
     ls -la
   -
    name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
     username: ${{ vars.DOCKER_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
   -
    name: Set up QEMU
    uses: docker/setup-qemu-action@v3
   -
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
   -
    name: Build backend (backend-build stage)
    uses: docker/build-push-action@v6
    with:
     target: backend-build
     context: ../..
     platforms: linux/amd64,linux/arm64
     file: Dockerfile
     push: false
   -
    name: Build and push final backend (final-backend stage)
    uses: docker/build-push-action@v6
    with:
     target: final-backend
     platforms: linux/amd64,linux/arm64
     context: ../..
     file: Dockerfile
     push: true
     tags: ${{ vars.DOCKER_USERNAME }}/quill-backend:latest
